const Items = [
  {
    id: "itm001",
    name: "Cordless Drill",
    description: "18V cordless drill, lightly used.",
    category: "Tools",
    owner: "Alice Johnson",
    condition: "Good",
    available: "yes",
    image: "https://images.toolworld.in/product/GSR120LSI-1.png",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm002",
    name: "Camping Tent",
    description: "4-person waterproof tent, easy setup.",
    category: "Outdoors",
    owner: "Brian Lee",
    condition: "Excellent",
    available: "yes",
    image: "https://himmaleh.in/cdn/shop/files/DSC06300-5.webp?v=1718474840",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm003",
    name: "Crock Pot",
    description: "Large 6-quart slow cooker, works great.",
    category: "Kitchen",
    owner: "Samantha Green",
    condition: "Very Good",
    available: "no",
    image: "https://images-cdn.ubuy.co.in/67c65bdd6d57f2292473096d-crock-pot-2-quart-round-manual-slow.jpg",
    borrowedBy: "Prachi Patel",
    sold: false,
  },
  {
    id: "itm004",
    name: "Yoga Mat",
    description: "Non-slip yoga mat, 6mm thick, blue color.",
    category: "Fitness",
    owner: "Ravi Mehra",
    condition: "Good",
    available: "yes",
    image: "https://rukminim2.flixcart.com/image/1200/1200/xif0q/sport-mat/o/0/h/-original-imaghgy547nacywa.jpeg",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm005",
    name: "Ladder",
    description: "6-foot aluminum step ladder, sturdy.",
    category: "Tools",
    owner: "Dana Wang",
    condition: "Good",
    available: "yes",
    image: "https://wernerco.widen.net/content/9ggwlztzl7/jpeg/6206_PI_Hero.jpeg?w=1200&h=1200&position=c&color=ffffffff&quality=100&u=qlpvmu",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm006",
    name: "Board Game: Settlers of Catan",
    description: "Complete set, all pieces included.",
    category: "Games",
    owner: "Luis García",
    condition: "Like New",
    available: "yes",
    image: "https://howtoplaycatan.com/wp-content/uploads/2022/11/Catan_board-removebg-preview.png",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm007",
    name: "Dumbell Pair 10 kgs",
    description: "Rubber coated 10kg dumbell pair",
    category: "Fitness",
    owner: "Jitesh Balani",
    condition: "Excellent",
    available: "yes",
    image: "https://m.media-amazon.com/images/I/31ra5v+dzuL._UF894,1000_QL80_.jpg",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm008",
    name: "Screwdriver Set",
    description: "et of 6 different screwdrivers with extension lever.",
    category: "Tools",
    owner: "Jitesh Balani",
    condition: "Very good",
    available: "yes",
    image: "https://dqvd9g622ecnq.cloudfront.net/media/webp_image/catalog/product/cache/740696d8dc5da3e55e0d9f1769f31d60/2/8/284400024677-1.webp",
    borrowedBy: null,
    sold: false,
  },
  {
    id: "itm009",
    name: "Chessbase Chess Board",
    description: "World's smartest electronic chess board.",
    category: "Games",
    owner: "Jitesh Balani",
    condition: "Very Good",
    available: "yes",
    image: "https://en.chessbase.com/portals/all/2016/Square%20Off/Square%20off-03_1.jpg",
    borrowedBy: null,
    sold: false,
  }
];

export default Items;
